In [28]:
import os
import pandas as pd

# Folder containing the CSV files
folder_path = 'data/'

# List all CSV files in the folder
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

# Loop through each file and extract useful information
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    
    # Load the CSV file into a pandas DataFrame
    df = pd.read_csv(file_path)
    
    # Get the file size
    file_size = os.path.getsize(file_path)  # in bytes
    
    # Get column names
    columns = df.columns.tolist()
    
    # Get the shape of the DataFrame
    num_rows, num_columns = df.shape
    
    # Get data types of each column
    column_types = df.dtypes.to_dict()
    
    # Count missing values
    missing_values = df.isnull().sum().to_dict()
    
    # Descriptive statistics for numerical columns
    descriptive_stats = df.describe()
    
    # Get the first two rows
    first_two_rows = df.head(2)
    
    # Print the file information
    print(f"File: {file}")
    print(f"Columns: {columns}")
    print(f"Shape (Rows x Columns): {num_rows} x {num_columns}")
    print(f"Data Types: {column_types}")
    print(f"Missing Values: {missing_values}")
    # print(f"Descriptive Statistics:\n{descriptive_stats}")
    print(f"First Two Rows:\n{first_two_rows}")
    print("-" * 50)

File: features_attributes.csv
Columns: ['Customer_ID', 'Name', 'Age', 'SSN', 'Occupation', 'snapshot_date']
Shape (Rows x Columns): 12500 x 6
Data Types: {'Customer_ID': dtype('O'), 'Name': dtype('O'), 'Age': dtype('O'), 'SSN': dtype('O'), 'Occupation': dtype('O'), 'snapshot_date': dtype('O')}
Missing Values: {'Customer_ID': 0, 'Name': 0, 'Age': 0, 'SSN': 0, 'Occupation': 0, 'snapshot_date': 0}
First Two Rows:
  Customer_ID            Name Age          SSN Occupation snapshot_date
0  CUS_0x1000  Alistair Barrf  18  913-74-1218     Lawyer    2023-05-01
1  CUS_0x1009          Arunah  26  063-67-6938   Mechanic    2025-01-01
--------------------------------------------------
File: features_financials.csv
Columns: ['Customer_ID', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'snapshot_date']
Shape (Rows x Columns): 12500 x 22
Data Types: {'Customer_ID': dtype('O'), 'Annual_Income': dtype('O'), 'Monthly_Inhand_Salary': dtype('float64'), 'Num_Bank_Accounts': dtype('int64'), 'Num_Credit_Card': dtype('int64'), 'Interest_Rate': dtype('int64'), 'Num_of_Loan': dtype('O'), 'Type_of_Loan': dtype('O'), 'Delay_from_due_date': dtype('int64'), 'Num_of_Delayed_Payment': dtype('O'), 'Changed_Credit_Limit': dtype('O'), 'Num_Credit_Inquiries': dtype('float64'), 'Credit_Mix': dtype('O'), 'Outstanding_Debt': dtype('O'), 'Credit_Utilization_Ratio': dtype('float64'), 'Credit_History_Age': dtype('O'), 'Payment_of_Min_Amount': dtype('O'), 'Total_EMI_per_month': dtype('float64'), 'Amount_invested_monthly': dtype('O'), 'Payment_Behaviour': dtype('O'), 'Monthly_Balance': dtype('O'), 'snapshot_date': dtype('O')}
Missing Values: {'Customer_ID': 0, 'Annual_Income': 0, 'Monthly_Inhand_Salary': 0, 'Num_Bank_Accounts': 0, 'Num_Credit_Card': 0, 'Interest_Rate': 0, 'Num_of_Loan': 0, 'Type_of_Loan': 1426, 'Delay_from_due_date': 0, 'Num_of_Delayed_Payment': 0, 'Changed_Credit_Limit': 0, 'Num_Credit_Inquiries': 0, 'Credit_Mix': 0, 'Outstanding_Debt': 0, 'Credit_Utilization_Ratio': 0, 'Credit_History_Age': 0, 'Payment_of_Min_Amount': 0, 'Total_EMI_per_month': 0, 'Amount_invested_monthly': 0, 'Payment_Behaviour': 0, 'Monthly_Balance': 0, 'snapshot_date': 0}
First Two Rows:
  Customer_ID Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
0  CUS_0x1000      30625.94            2706.161667                  6
1  CUS_0x1009     52312.68_            4250.390000                  6

   Num_Credit_Card  Interest_Rate Num_of_Loan  \
0                5             27           2
1                5             17           4

                                        Type_of_Loan  Delay_from_due_date  \
0          Credit-Builder Loan, and Home Equity Loan                   57
1  Not Specified, Home Equity Loan, Credit-Builde...                    5

  Num_of_Delayed_Payment  ... Credit_Mix  Outstanding_Debt  \
0                     26  ...        Bad           1562.91
1                     18  ...          _            202.68

  Credit_Utilization_Ratio     Credit_History_Age  Payment_of_Min_Amount  \
0                30.077191  10 Years and 9 Months                    Yes
1                40.286997  31 Years and 0 Months                    Yes

  Total_EMI_per_month Amount_invested_monthly  \
0           42.941090       77.31427572208112
1          108.366467       58.66019164829086

                  Payment_Behaviour     Monthly_Balance snapshot_date
0  High_spent_Medium_value_payments  400.36080052211616    2023-05-01
1  High_spent_Medium_value_payments  508.01234122645366    2025-01-01

[2 rows x 22 columns]
--------------------------------------------------
File: feature_clickstream.csv
Columns: ['fe_1', 'fe_2', 'fe_3', 'fe_4', 'fe_5', 'fe_6', 'fe_7', 'fe_8', 'fe_9', 'fe_10', 'fe_11', 'fe_12', 'fe_13', 'fe_14', 'fe_15', 'fe_16', 'fe_17', 'fe_18', 'fe_19', 'fe_20', 'Customer_ID', 'snapshot_date']
Shape (Rows x Columns): 215376 x 22
Data Types: {'fe_1': dtype('int64'), 'fe_2': dtype('int64'), 'fe_3': dtype('int64'), 'fe_4': dtype('int64'), 'fe_5': dtype('int64'), 'fe_6': dtype('int64'), 'fe_7': dtype('int64'), 'fe_8': dtype('int64'), 'fe_9': dtype('int64'), 'fe_10': dtype('int64'), 'fe_11': dtype('int64'), 'fe_12': dtype('int64'), 'fe_13': dtype('int64'), 'fe_14': dtype('int64'), 'fe_15': dtype('int64'), 'fe_16': dtype('int64'), 'fe_17': dtype('int64'), 'fe_18': dtype('int64'), 'fe_19': dtype('int64'), 'fe_20': dtype('int64'), 'Customer_ID': dtype('O'), 'snapshot_date': dtype('O')}
Missing Values: {'fe_1': 0, 'fe_2': 0, 'fe_3': 0, 'fe_4': 0, 'fe_5': 0, 'fe_6': 0, 'fe_7': 0, 'fe_8': 0, 'fe_9': 0, 'fe_10': 0, 'fe_11': 0, 'fe_12': 0, 'fe_13': 0, 'fe_14': 0, 'fe_15': 0, 'fe_16': 0, 'fe_17': 0, 'fe_18': 0, 'fe_19': 0, 'fe_20': 0, 'Customer_ID': 0, 'snapshot_date': 0}
First Two Rows:
   fe_1  fe_2  fe_3  fe_4  fe_5  fe_6  fe_7  fe_8  fe_9  fe_10  ...  fe_13  \
0    63   118    80   121    55   193   111   112  -101     83  ...    -16
1  -108   182   123     4   -56    27    25    -6   284    222  ...    -14

   fe_14  fe_15  fe_16  fe_17  fe_18  fe_19  fe_20  Customer_ID  snapshot_date
0    -81   -126    114     35     85    -73     76   CUS_0x1037     2023-01-01
1    -96    200     35    130     94    111     75   CUS_0x1069     2023-01-01

[2 rows x 22 columns]
--------------------------------------------------
File: lms_loan_daily.csv
Columns: ['loan_id', 'Customer_ID', 'loan_start_date', 'tenure', 'installment_num', 'loan_amt', 'due_amt', 'paid_amt', 'overdue_amt', 'balance', 'snapshot_date']
Shape (Rows x Columns): 137500 x 11
Data Types: {'loan_id': dtype('O'), 'Customer_ID': dtype('O'), 'loan_start_date': dtype('O'), 'tenure': dtype('int64'), 'installment_num': dtype('int64'), 'loan_amt': dtype('int64'), 'due_amt': dtype('float64'), 'paid_amt': dtype('float64'), 'overdue_amt': dtype('float64'), 'balance': dtype('float64'), 'snapshot_date': dtype('O')}
Missing Values: {'loan_id': 0, 'Customer_ID': 0, 'loan_start_date': 0, 'tenure': 0, 'installment_num': 0, 'loan_amt': 0, 'due_amt': 0, 'paid_amt': 0, 'overdue_amt': 0, 'balance': 0, 'snapshot_date': 0}
First Two Rows:
                 loan_id Customer_ID loan_start_date  tenure  installment_num  \
0  CUS_0x1000_2023_05_01  CUS_0x1000      2023-05-01      10                0
1  CUS_0x1000_2023_05_01  CUS_0x1000      2023-05-01      10                1

   loan_amt  due_amt  paid_amt  overdue_amt  balance snapshot_date
0     10000      0.0       0.0          0.0  10000.0    2023-05-01
1     10000   1000.0    1000.0          0.0   9000.0    2023-06-01
--------------------------------------------------

In [5]:
df_1 = pd.read_csv(r'data\feature_clickstream.csv')
df_2 = pd.read_csv(r'data\features_attributes.csv')
df_3 = pd.read_csv(r"data\features_financials.csv")
df_4 = pd.read_csv(r'data\lms_loan_daily.csv')

In [6]:
df_1

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,...,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20,Customer_ID,snapshot_date
0,63,118,80,121,55,193,111,112,-101,83,...,-16,-81,-126,114,35,85,-73,76,CUS_0x1037,2023-01-01
1,-108,182,123,4,-56,27,25,-6,284,222,...,-14,-96,200,35,130,94,111,75,CUS_0x1069,2023-01-01
2,-13,8,87,166,214,-98,215,152,129,139,...,26,86,171,125,-130,354,17,302,CUS_0x114a,2023-01-01
3,-85,45,200,89,128,54,76,51,61,139,...,172,96,174,163,37,207,180,118,CUS_0x1184,2023-01-01
4,55,120,226,-86,253,97,107,68,103,126,...,76,43,183,159,-26,104,118,184,CUS_0x1297,2023-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215371,414,22,72,57,142,192,11,139,24,63,...,179,91,20,189,-35,-19,15,66,CUS_0xdf6,2024-12-01
215372,116,-124,-108,212,-21,227,146,112,186,-65,...,38,226,319,98,9,152,17,14,CUS_0xe23,2024-12-01
215373,237,-3,-49,375,144,41,-170,324,19,266,...,7,102,64,191,124,220,231,75,CUS_0xe4e,2024-12-01
215374,5,67,211,83,207,-41,325,14,-18,41,...,109,266,28,157,131,116,101,131,CUS_0xedd,2024-12-01
215375,196,11,115,94,167,227,119,255,32,96,...,120,85,363,74,-26,107,104,186,CUS_0xfe4,2024-12-01

In [7]:
df_2

,Customer_ID,Name,Age,SSN,Occupation,snapshot_date
0,CUS_0x1000,Alistair Barrf,18,913-74-1218,Lawyer,2023-05-01
1,CUS_0x1009,Arunah,26,063-67-6938,Mechanic,2025-01-01
2,CUS_0x100b,Shirboni,19,#F%$D@*&8,Media_Manager,2024-03-01
3,CUS_0x1011,Schneyerh,44,793-05-8223,Doctor,2023-11-01
4,CUS_0x1013,Cameront,44,930-49-9615,Mechanic,2023-12-01
...,...,...,...,...,...,...
12495,CUS_0xff3,Somervilled,55,#F%$D@*&8,Scientist,2024-06-01
12496,CUS_0xff4,Poornimaf,37,655-05-7666,Entrepreneur,2024-12-01
12497,CUS_0xff6,Shieldsb,19,541-92-8371,Doctor,2024-10-01
12498,CUS_0xffc,Brads,18,226-86-7294,Musician,2024-01-01
12499,CUS_0xffd,Damouniq,30,832-88-8320,Scientist,2024-03-01

In [8]:
df_3

,Customer_ID,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,snapshot_date
0,CUS_0x1000,30625.94,2706.161667,6,5,27,2,"Credit-Builder Loan, and Home Equity Loan",57,26,...,Bad,1562.91,30.077191,10 Years and 9 Months,Yes,42.941090,77.31427572208112,High_spent_Medium_value_payments,400.36080052211616,2023-05-01
1,CUS_0x1009,52312.68_,4250.390000,6,5,17,4,"Not Specified, Home Equity Loan, Credit-Builde...",5,18,...,_,202.68,40.286997,31 Years and 0 Months,Yes,108.366467,58.66019164829086,High_spent_Medium_value_payments,508.01234122645366,2025-01-01
2,CUS_0x100b,113781.38999999998,9549.782500,1,4,1,0,NaN,14,8,...,Good,1030.2,28.592943,15 Years and 10 Months,No,0.000000,617.0792665202719,High_spent_Small_value_payments,597.8989834797281,2024-03-01
3,CUS_0x1011,58918.47,5208.872500,3,3,17,3,"Student Loan, Credit-Builder Loan, and Debt Co...",27,13,...,Standard,473.14,27.829959,15 Years and 10 Months,Yes,123.434939,383.35084463651407,Low_spent_Medium_value_payments,294.1014665671429,2023-11-01
4,CUS_0x1013,98620.98,7962.415000,3,3,6,3,"Student Loan, Debt Consolidation Loan, and Per...",12,9,...,Good,1233.51,26.524864,17 Years and 10 Months,No,228.018084,332.3337079767732,High_spent_Medium_value_payments,485.8897083704929,2023-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,CUS_0xff3,17032.785,1176.398750,0,6,2,3,"Personal Loan, Mortgage Loan, and Auto Loan",13,7_,...,Good,1229.08,26.915577,17 Years and 3 Months,No,33.299764,81.19585741743609,Low_spent_Small_value_payments,293.14425404017936,2024-06-01
12496,CUS_0xff4,25546.26,2415.855000,8,7,14,5_,"Not Specified, Student Loan, Student Loan, Cre...",15,13_,...,Standard,758.44,39.333488,18 Years and 9 Months,Yes,101.328637,189.81586133347676,Low_spent_Medium_value_payments,230.44100130267208,2024-12-01
12497,CUS_0xff6,117639.92,9727.326667,5,6,1,2,"Home Equity Loan, and Auto Loan",-3,7,...,Good,338.3,32.871853,24 Years and 11 Months,No,126.638453,534.0885271982645,Low_spent_Medium_value_payments,592.0056861539196,2024-10-01
12498,CUS_0xffc,60877.17,5218.097500,6,8,27,8,"Credit-Builder Loan, Payday Loan, Not Specifie...",46,14,...,_,1300.13,29.026498,13 Years and 1 Months,Yes,272.809169,46.4256138380274,High_spent_Large_value_payments,442.5749666782518,2024-01-01
12499,CUS_0xffd,41398.44,3749.870000,8,7,13,6,"Auto Loan, Payday Loan, Payday Loan, Mortgage ...",23,11,...,Standard,1701.88,39.916655,18 Years and 9 Months,Yes,182.976649,42.57571978536272,High_spent_Large_value_payments,389.434630761722,2024-03-01

In [9]:
df_4

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date
0,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,0,10000,0.0,0.0,0.0,10000.0,2023-05-01
1,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,1,10000,1000.0,1000.0,0.0,9000.0,2023-06-01
2,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2023-07-01
3,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,3,10000,1000.0,0.0,1000.0,8000.0,2023-08-01
4,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,4,10000,1000.0,2000.0,0.0,6000.0,2023-09-01
...,...,...,...,...,...,...,...,...,...,...,...
137495,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,6,10000,1000.0,1000.0,0.0,4000.0,2024-09-01
137496,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,7,10000,1000.0,1000.0,0.0,3000.0,2024-10-01
137497,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,8,10000,1000.0,1000.0,0.0,2000.0,2024-11-01
137498,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,9,10000,1000.0,1000.0,0.0,1000.0,2024-12-01
137499,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,10,10000,1000.0,1000.0,0.0,0.0,2025-01-01

In [21]:
df_1.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215376 entries, 0 to 215375
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   fe_1           215376 non-null  int64
 1   fe_2           215376 non-null  int64
 2   fe_3           215376 non-null  int64
 3   fe_4           215376 non-null  int64
 4   fe_5           215376 non-null  int64
 5   fe_6           215376 non-null  int64
 6   fe_7           215376 non-null  int64
 7   fe_8           215376 non-null  int64
 8   fe_9           215376 non-null  int64
 9   fe_10          215376 non-null  int64
 10  fe_11          215376 non-null  int64
 11  fe_12          215376 non-null  int64
 12  fe_13          215376 non-null  int64
 13  fe_14          215376 non-null  int64
 14  fe_15          215376 non-null  int64
 15  fe_16          215376 non-null  int64
 16  fe_17          215376 non-null  int64
 17  fe_18          215376 non-null  int64
 18  fe_19          215376 non-null  int64
 19  fe_20          215376 non-null  int64
 20  Customer_ID    215376 non-null  object
 21  snapshot_date  215376 non-null  object
dtypes: int64(20), object(2)
memory usage: 36.2+ MB

In [25]:
df_2.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    12500 non-null  object
 1   Name           12500 non-null  object
 2   Age            12500 non-null  object
 3   SSN            12500 non-null  object
 4   Occupation     12500 non-null  object
 5   snapshot_date  12500 non-null  object
dtypes: object(6)
memory usage: 586.1+ KB

In [26]:
df_3.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               12500 non-null  object
 1   Annual_Income             12500 non-null  object
 2   Monthly_Inhand_Salary     12500 non-null  float64
 3   Num_Bank_Accounts         12500 non-null  int64
 4   Num_Credit_Card           12500 non-null  int64
 5   Interest_Rate             12500 non-null  int64
 6   Num_of_Loan               12500 non-null  object
 7   Type_of_Loan              11074 non-null  object
 8   Delay_from_due_date       12500 non-null  int64
 9   Num_of_Delayed_Payment    12500 non-null  object
 10  Changed_Credit_Limit      12500 non-null  object
 11  Num_Credit_Inquiries      12500 non-null  float64
 12  Credit_Mix                12500 non-null  object
 13  Outstanding_Debt          12500 non-null  object
 14  Credit_Utilization_Ratio  12500 non-null  float64
 15  Credit_History_Age        12500 non-null  object
 16  Payment_of_Min_Amount     12500 non-null  object
 17  Total_EMI_per_month       12500 non-null  float64
 18  Amount_invested_monthly   12500 non-null  object
 19  Payment_Behaviour         12500 non-null  object
 20  Monthly_Balance           12500 non-null  object
 21  snapshot_date             12500 non-null  object
dtypes: float64(4), int64(4), object(14)
memory usage: 2.1+ MB

In [27]:
df_4.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137500 entries, 0 to 137499
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   loan_id          137500 non-null  object
 1   Customer_ID      137500 non-null  object
 2   loan_start_date  137500 non-null  object
 3   tenure           137500 non-null  int64
 4   installment_num  137500 non-null  int64
 5   loan_amt         137500 non-null  int64
 6   due_amt          137500 non-null  float64
 7   paid_amt         137500 non-null  float64
 8   overdue_amt      137500 non-null  float64
 9   balance          137500 non-null  float64
 10  snapshot_date    137500 non-null  object
dtypes: float64(4), int64(3), object(4)
memory usage: 11.5+ MB